// utils/getImagePath.ts
const categoryImageMap: Record<string, any> = {
  Wind: require('./../assets/weatherConditionPNG/windpng.png'),
  Suncloudy: require('./../assets/weatherConditionPNG/sun.png'),
  Sun: require('./../assets/weatherConditionPNG/sun.png'),
  Storm: require('./../assets/weatherConditionPNG/storm.png'),
  Snowy: require('./../assets/weatherConditionPNG/snowy.png'),
  'Severe Weather': require('./../assets/weatherConditionPNG/severeweather.png'),
  Rainy: require('./../assets/weatherConditionPNG/rainy.png'),
  'Cloudy Light Rain': require('./../assets/weatherConditionPNG/cloudylightrain.png'),
  Cloudy: require('./../assets/weatherConditionPNG/cloudy.png'),
  Cloud: require('./../assets/weatherConditionPNG/cloud.png'),
};

const conditionCategoryMap: Record<string, string> = {
  Blizzard: 'Wind',
  'Partly cloudy': 'Cloudy',
  'Partly Cloudy ': 'Cloudy',
  Sunny: 'Sun',
  Clear: 'Cloudy',
  'Clear ': 'Cloudy',
  'Cloudy ': 'Cloudy',
  'Thundery outbreaks possible': 'Storm',
  'Patchy light rain with thunder': 'Storm',
  'Moderate or heavy rain with thunder': 'Storm',
  'Patchy light snow with thunder': 'Storm',
  'Moderate or heavy snow with thunder': 'Storm',
  'Patchy snow possible': 'Snowy',
  'Blowing snow': 'Snowy',
  'Patchy light snow': 'Snowy',
  'Light snow': 'Snowy',
  'Patchy moderate snow': 'Snowy',
  'Moderate snow': 'Snowy',
  'Patchy heavy snow': 'Snowy',
  'Heavy snow': 'Snowy',
  'Ice pellets': 'Snowy',
  'Light snow showers': 'Snowy',
  'Moderate or heavy snow showers': 'Snowy',
  'Light showers of ice pellets': 'Snowy',
  'Moderate or heavy showers of ice pellets': 'Snowy',
  'Moderate rain at times': 'Rainy',
  'Moderate rain': 'Rainy',
  'Heavy rain at times': 'Rainy',
  'Heavy rain': 'Rainy',
  'Moderate or heavy freezing rain': 'Rainy',
  'Moderate or heavy rain shower': 'Rainy',
  'Torrential rain shower': 'Rainy',
  'Patchy light rain': 'Cloudy Light Rain',
  'Light rain': 'Cloudy Light Rain',
  'Light rain shower': 'Cloudy Light Rain',
  Cloudy: 'Cloudy',
  Overcast: 'Cloudy',
  'Overcast ': 'Cloudy',
  Fog: 'Cloudy',
  'Freezing fog': 'Cloudy',
  Mist: 'Cloud',
  'Patchy rain possible': 'Cloud',
  'Patchy rain nearby': 'Cloud',
  'Patchy sleet possible': 'Cloud',
  'Patchy freezing drizzle possible': 'Cloud',
  'Patchy light drizzle': 'Cloud',
  'Light drizzle': 'Cloud',
  'Freezing drizzle': 'Cloud',
  'Heavy freezing drizzle': 'Cloud',
  'Light freezing rain': 'Cloud',
  'Light sleet': 'Cloud',
  'Moderate or heavy sleet': 'Cloud',
  'Light sleet showers': 'Cloud',
  'Moderate or heavy sleet showers': 'Cloud',
};

export function getImageForCondition(condition: string): any | null {
  const category = conditionCategoryMap[condition];
  if (!category) return null;
  return categoryImageMap[category] ?? null;
}
